version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
    ports:
      - 443:443
      - 80:80
    expose:
      - 80
      - 443
    networks:
      - vcfvisualize

  postgres:
    image: postgres:latest
    restart: always
    expose:
      - 5432
    ports:
      - 10938:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'sample'
    volumes:
      # change ~/data/vv/postgres to change the location of the postgresql database which handles patient samples
      - ~/data/vv/postgres:/var/lib/postgresql/data
    networks:
      - vcfvisualize

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    expose:
      - 3306
    volumes:
      # change ~/data/vv/mysql to change the location of the mysql database which stores user credentials and access rights
      - ~/data/vv/mysql:/var/lib/mysql
    networks:
      - vcfvisualize
    depends_on:
      - postgres

  core:
    restart: always
    build: core/
    environment:
      SPRING_APPLICATION_JSON: '{
        "database.postgres.url": "postgres:5432/sample",
        "database.postgres.user": "postgres",
        "database.postgres.password": "password",
        "database.mysql.host": "mysql",
        "database.mysql.user": "root",
        "database.mysql.password": "password",
        "storage.reads.usegoogle": "false",
        "storage.reads.google.credentials": "",
        "storage.reads.google.projectid": "",
        "storage.reads.google.bucketname": ""
      }'
    volumes:
      - ~/data/vv/core:/var
      # change ~/data/files/ to change the location of your bam files
      - ~/data/WGS_data:/bam
    networks:
      - vcfvisualize
    depends_on:
      - mysql
    expose:
      - 8080

  web:
    restart: always
    build: web/
    networks:
      - vcfvisualize
    depends_on:
      - core
    expose:
      - 3000

networks:
    vcfvisualize:
        driver: bridge
volumes:
    vcf-visualize:

